---

# Sets the amount of time the cache is valid
#
apt_cache_valid_time: {{ apt.cache_time | default('60 * 60') }}

# APT by default does not specify wether or not "recommended" packages should
# be installed
#
apt_install_recommends: {{ apt.recommended | default('false') }}

# APT by default does not specify wether or not "suggested" packages should be
# installed
#
apt_install_sugggets: {{ apt.suggested | default('false') }}
